/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;

public class ListZipperTest {

    @Test
    public void testZipWithEqualLengthLists() {
        List<Integer> list1 = Arrays.asList(1, 3, 5);
        List<Integer> list2 = Arrays.asList(2, 4, 6);
        List<Integer> expected = Arrays.asList(1, 2, 3, 4, 5, 6);
        assertEquals(expected, ListZipper.zip(list1, list2));
    }

    @Test
    public void testZipWithFirstListLonger() {
        List<String> list1 = Arrays.asList("a", "b", "c", "d");
        List<String> list2 = Arrays.asList("1", "2");
        List<String> expected = Arrays.asList("a", "1", "b", "2", "c", "d");
        assertEquals(expected, ListZipper.zip(list1, list2));
    }

    @Test
    public void testZipWithSecondListLonger() {
        List<String> list1 = Arrays.asList("x");
        List<String> list2 = Arrays.asList("1", "2", "3");
        List<String> expected = Arrays.asList("x", "1", "2", "3");
        assertEquals(expected, ListZipper.zip(list1, list2));
    }

    @Test
    public void testZipWithEmptyLists() {
        List<Object> list1 = Collections.emptyList();
        List<Object> list2 = Collections.emptyList();
        List<Object> expected = Collections.emptyList();
        assertEquals(expected, ListZipper.zip(list1, list2));
    }

    @Test
    public void testZipWithCustomObjects() {
        class Person {
            String name;
            Person(String name) { this.name = name; }
            @Override
            public boolean equals(Object o) {
                if (!(o instanceof Person)) return false;
                return Objects.equals(name, ((Person) o).name);
            }
            @Override
            public int hashCode() {
                return Objects.hash(name);
            }
        }

        List<Person> list1 = Arrays.asList(new Person("Alice"), new Person("Bob"));
        List<Person> list2 = Arrays.asList(new Person("Xander"));
        List<Person> expected = Arrays.asList(new Person("Alice"), new Person("Xander"), new Person("Bob"));
        assertEquals(expected, ListZipper.zip(list1, list2));
    }
}
